### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by Farhda** [DeviatorZ/league-account-checker#101]
Hi I hope that you are doing alright. 

This is my first time using the program and I keep getting this error:
capsolver.com Failed: InvalidRequestError: invalid task data: The website is currently under maintenance
2024-03-05 17:41:42 [ERROR] ﻿xxxxxxxxx Failed to get Captcha token! Retrying...

Any suggestions ?

**Comment by Farhda** [comment]
nvm I sorted the captcha problem.

Now if you don't mind me asking. I want to export loot items by name if possible.

Is that possible ?

**Comment by justinjd00** [comment]
hi is it working for u @Farhda `

**Comment by iheb-mahmoud** [comment]
is it working guys ?

**Comment by Farhda** [comment]
Yes @justinjd00 @iheb-mahmoud . wanna join me on discord to show you how it works ?

**Comment by justinjd00** [comment]
@Farhda yes pls send your dc
