### ISSUE TITLE
Need help with this weird error

### ISSUE THREAD

**Issue by kamihyp** [DeviatorZ/league-account-checker#15]
When i start it with my accounts it says : [ERROR] Request exception: PUT : https://127.0.0.1:50000/rso-auth/v1/session/credentials
![image](https://user-images.githubusercontent.com/77826401/225383014-eb8949ca-af8b-4558-ab38-3115506a2350.png)

**Comment by DeviatorZ** [comment]
Hi, since it reached the login phase - riot client has been launched successfully. I pushed a new update - added a retry limit so some accounts might get skipped. Let me know if it happens to all accounts or only some. Status code is now also displayed in console so it could be helpful if you could send me a screenshot if it still happens.

**Comment by kamihyp** [comment]
After that fix i got new bug idk whats happening 
![image](https://user-images.githubusercontent.com/77826401/225650334-d50fa6fe-f704-4d4f-b2a6-694210cf49b0.png)

**Comment by DeviatorZ** [comment]
Another possible cause - some servers run on different patches for some reason so you need to manually login on an account on that server and allow league client to update. Since the checker runs multiple threads patching is disabled.

**Comment by kubakakauko** [comment]
I know this is clossed however i wanted to mention that it seems to still be the issue. 
I tried it on a quite a few regions and it happened on all of them.

**Comment by DeviatorZ** [comment]
1. It would help me if you'd send me your device specs and OS + how many threads are you running.
2. Is it the same request that's failing and what's the status code?
3. Is your internet connection stable?
4. Did you update the client manually? I'm planning to add client updating to checker when it's ran single threaded.

**Comment by hywj212** [comment]
> 
i have the same error
1.win10,only 1 thread running
2.yes,all fail is same code
3.yes
4.yes

**Comment by DeviatorZ** [comment]
Hi, I just pushed an update for client updating when it's ran single-threaded. I cannot find a way to reproduce this specific error. If the issue persists contact me on discord Deviator#0059
