### ISSUE TITLE
too many login attempts

### ISSUE THREAD

**Issue by ymc989** [DeviatorZ/league-account-checker#23]
i really want to thank you for making this and appriciate the sharing, but whats the point of the checker if its checking the accounts on the main device ip, or even if connected with a vpn it will still get limited with too many login attempts for like 5 accounts or so, how can someone avoid this? maybe you can add proxy? i really want to learn how

**Comment by DeviatorZ** [comment]
Hi, It's meant to be used with your own accounts and not with random login details. If you do have a high amount of invalid logins I can only recommend running single threaded.
