### ISSUE TITLE
Unhandled exception. Contact developer! 

### ISSUE THREAD

**Issue by He15ndy** [DeviatorZ/league-account-checker#34]
![image](https://github.com/DeviatorZ/league-account-checker/assets/71564798/5d7df2cc-b3dd-47cb-a6ab-fb20d9b3126e)
it worked yesterday, but after the update it doesn't work anymore

**Comment by DeviatorZ** [comment]
Hey, this is caused by the tier of unranked accounts changing from "NONE" to "" in the API. It should be fixed now!
