### ISSUE TITLE
ERROR - Unhandled exception. Contact developer! Retrying...

### ISSUE THREAD

**Issue by aryahalakove** [DeviatorZ/league-account-checker#37]
2023-06-02 11:53:14 [INFO] Starting tasks...
2023-06-02 11:53:14 [INFO] Executing tasks on account: *****
2023-06-02 11:53:44 [ERROR] Unhandled exception. Contact developer! Retrying...
2023-06-02 11:53:44 [ERROR] 'NA'

works on old version but sometimes gives this error on new version.

**Comment by DeviatorZ** [comment]
Does it happen on specific accounts or servers?

**Comment by DeviatorZ** [comment]
I managed to find an older league version and reproduce the same error. API is only changed for the newest update so you should run 1 account with 1 thread for the client to update or update manually.

**Comment by aryahalakove** [comment]
As you know the old version of checker doesn't update the league, I need to update manually so there's no problem with league updates, It gives this error with some accounts that I didn't managed to find what's the problem

**Comment by DeviatorZ** [comment]
It could be that some servers don't use the changed API so I added backward compatibility. You can find the changes in the dev branch (https://github.com/DeviatorZ/league-account-checker/tree/dev). If you're still getting the error then it's a different cause altogether.

**Comment by aryahalakove** [comment]
Thanks for update, I will check when I'm available today and also all accounts with that error was in EUW server.
