### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alexuk79** [DeviatorZ/league-account-checker#39]
hi, its doesn't work for me 
 
![error](https://github.com/DeviatorZ/league-account-checker/assets/132964641/8d904bb8-9bce-4233-bc6a-8c686ef42dac)

**Comment by DeviatorZ** [comment]
You're using an old version. Download the newest one.

**Comment by alexuk79** [comment]
where i can find it, i downloaded zip archive from here 
![11d11892f554729ad2ae3c947fcacc67](https://github.com/DeviatorZ/league-account-checker/assets/132964641/1854dd0b-a311-46e0-8ac7-c5e924dbaedc)

**Comment by DeviatorZ** [comment]
Yes, there.

**Comment by alexuk79** [comment]
redownloaded, works now, ty
