### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alexuk79** [DeviatorZ/league-account-checker#44]
hi, have this error **LeagueConnection - Connection failure. Retrying...** to any accounts with correct credentials, tried opening with admin cmd main.pyw didn't help. When i manually open an account, without a checker, all works. Path to RiotClientServices.exe and LeagueClient.exe is correct. Also tried 1 thread or more, same result, all tasks disabled(event shop/crafting/disenchanting)

**Comment by alexuk79** [comment]
nvm, its probably server issues

**Comment by DeviatorZ** [comment]
Hi, it could also be the event shop tasks (disable them until I patch them or until a new event is up). Riot changed how event shop API behaves when there's no event running. I'll fix it when I get time.
