### ISSUE TITLE
REQUEST: Skin Chromas

### ISSUE THREAD

**Issue by aryahalakove** [DeviatorZ/league-account-checker#47]
Hi, can you add Skin Chromas to checker ?

**Comment by DeviatorZ** [comment]
Hi, I'll consider it. What would be needed? Ability to export information about owned chromas and chroma shards?

**Comment by aryahalakove** [comment]
Hi, thanks for your response. It would be awesome if there's ability to export owned chromas.

**Comment by DeviatorZ** [comment]
I can't find any API for chroma names. I could only get IDs, color codes, and a link to an image with how the chroma looks.

**Comment by aryahalakove** [comment]
Probably you need to match color codes with names manually, I found here for matching chroma names: https://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions.json
for example 
Sapphire = #2756CE 
Obisidan = #27211C
if it works you can check

**Comment by DeviatorZ** [comment]
Added it in [https://github.com/DeviatorZ/league-account-checker/tree/dev](Dev branch). Still need to test if chroma names are in english on a non-english region but don't have an account for that atm.

**Comment by aryahalakove** [comment]
Thanks for fast response, I will try it when I'm available

**Comment by aryahalakove** [comment]
I just checked an account with 991 skins and 540+ chromas, 
exported datas are: 
"ownedSkinsCount": 1191 "ownedSkinChromasCount": 349
I couldn't check every skin or chroma name one by one so I just checked with Count vars and it's inaccurate.

**Comment by DeviatorZ** [comment]
total is 1540 so it seems close. It could be that some chromas get added to the skin list. I'll take a look tomorrow. Could you find a chroma in the skin list by any chance and send the name?

**Comment by DeviatorZ** [comment]
I pushed an update. Please let me know if it's correct now.

**Comment by aryahalakove** [comment]
Hi, thanks for fast response, I just checked and it's correct now. I appreciate your work.
