### ISSUE TITLE
Please add export chests data in the account!THX!

### ISSUE THREAD

**Issue by Aimochier** [DeviatorZ/league-account-checker#48]
Please add export chests data in the account!THX! Example, how many amazon prime capeules, orbs, hex

**Comment by DeviatorZ** [comment]
Added a new export variable "otherLoot". It should contain all loot with a few exceptions:
  No champion/skin shards
  No mastery tokens
 
If you get "Unknown" loot feel free to make an issue that contains the "otherLoot" string and screenshots of all the loot in the account.

**Comment by Aimochier** [comment]
"otherLoot": "1x Unknown, 1x Unknown, 3x Key fragments, 1x Unknown, 1x Hextech Chest, 1x Unknown, 1x Unknown",
![1](https://github.com/DeviatorZ/league-account-checker/assets/100269599/fbec75cf-e969-405c-ad25-77497cb2c021)
![3](https://github.com/DeviatorZ/league-account-checker/assets/100269599/0db457f6-99d9-4104-b8d4-3f77ef60021f)
![2](https://github.com/DeviatorZ/league-account-checker/assets/100269599/eda34851-39e7-436a-8755-1505d11b49a4)

**Comment by Aimochier** [comment]
The second drop is amazon prime gaming.

**Comment by Aimochier** [comment]
I replied on the closed theme，Some unknown drops appeared, I uploaded pictures.




Aimer
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DeviatorZ/league-account-checker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 凌晨0:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DeviatorZ/league-account-checker] Please add export chests data in the account!THX! (Issue #48)





 
Added a new export variable "otherLoot". It should contain all loot with a few exceptions:
 No champion/skin shards
 No mastery tokens
 
If you get "Unknown" loot feel free to make an issue that contains the "otherLoot" string and screenshots of all the loot in the account.
