### ISSUE TITLE
question

### ISSUE THREAD

**Issue by alexuk79** [DeviatorZ/league-account-checker#51]
hi, idk why, but when i run checker, it seems like checker works only at 1 thread, even if i select more. Im saying this cuz i see only 1 riot client opened at taskbar (at windows), so i assume only 1 thread working at same time, and it affects to speed of checking accounts, not sure if this problem from my side or not.

**Comment by DeviatorZ** [comment]
Hi, are you using correct logins? There's an extra delay on invalid credentials to avoid getting rate limited. To validate how many clients are running check child processes of checker process in task manager.

**Comment by alexuk79** [comment]
i think it 50/50% login correct, there only 2 process in child processes of checker, and only 1 riot client works in same time

**Comment by DeviatorZ** [comment]
By default, the launch cooldown is 30s on invalid credentials. You can try editing "LAUNCH_COOLDOWN_ON_INVALID_CREDENTIALS" value in config.py to reduce the cooldown but beware it might cause you to get rate limited depending on % of accounts that you have with invalid logins.
