### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by alexuk79** [DeviatorZ/league-account-checker#59]
hi, have this errors to every accounts **RiotConnection:RequestException - PUT : /rso-auth/v1/session/credentials : 401. Retrying...** **RiotConnection:SessionException - League client launch timed out. Retrying...**

**Comment by DeviatorZ** [comment]
Hi, they added hCaptcha and changed login system. Working on it.

**Comment by DeviatorZ** [comment]
I pushed an update, should work now.
