### ISSUE TITLE
Login issues, rso rate limit -proxy support-

### ISSUE THREAD

**Issue by ariabox** [DeviatorZ/league-account-checker#60]
Hi, riot changed their login system few days ago, probably they added rate limit for rso endpoints, after 10-15 accounts, ip will be locked and doesn't let you login for a while i don't know how much time. If you can add proxy support it would be great. Thanks.

**Comment by ariabox** [comment]
also riot auth system has been changed, currently it's not working at all

**Comment by zasaky** [comment]
Hello please let us know when update is out :)

**Comment by DeviatorZ** [comment]
I've got a working solution that requires proxies and a captcha-solving service. Currently working on using a separate proxy for each client instead of rotating one proxy for all.

**Comment by zasaky** [comment]
Thank you very much for your feedback. If there's something we can do to support you please let us know. If u want you can add me on discord AnRa#2544 thank you

**Comment by ariabox** [comment]
Please add service support for capsolver and capmonster because others are very slow

**Comment by DeviatorZ** [comment]
After further testing, I realized that the global Windows proxy setting is bypassed and doesn't work (still need to investigate more), VPNs work but a lot of IPs are fully blocked. For now, I am adding support only for capmonster.cloud but might add others in the future. I'll try to get a working version out in the dev branch today (no IP changing for now).

**Comment by bilbil5** [comment]
@DeviatorZ hello deviatorz if you use discord, can i add you?

**Comment by zasaky** [comment]
Hello friend, what about not changing IP at all and ousing our own IP and a captcha service? We can help with the licenses. Please let us know what we can do to support you.
Happy weekend.

**Comment by DeviatorZ** [comment]
@bilbil5 You can add me:  _deviator_

**Comment by DeviatorZ** [comment]
@zasaky It works just like before but the rate limit has been reduced. Used to be able to launch a client every 5 seconds. Now 7 isn't enough. Tested with 10 seconds - 200 accounts in 50mins (nearly all logins correct and no tasks)

**Comment by zasaky** [comment]
@DeviatorZ  Thank you for your reply. I might have missunderstood, but i can not get the program to work. Maybe you meant that it is working on your test. I personally don't mind if it is way slower than before a s long as i can keep it working with my own IP. I have many accounts that i would like to check and i can leave it working all day if necessary. Anyways, if there's anything we can do to support you, just let us know.
Very thankful for your hardwork and dedication.

**Comment by DeviatorZ** [comment]
Currently, I'm still testing and I also need to captcha setting to the GUI before I can push an update to GitHub.

**Comment by ariabox** [comment]
Hello, I appreciate your hardwork, aldo for IP changing, what about just use requests proxy update for login endpoints ?

**Comment by nekrusss** [comment]
Hi! I think adding 2captha would be grate, the prices are low and its good. Its also trusted (and used) by maaaaany apps that need captcha bypass api.
[link for 2captcha](https://2captcha.com/)

**Comment by DeviatorZ** [comment]
@ariabox Hi, all requests outside the ones for the store (whose access token is obtained through the client) are sent to the local backend client which then sends requests to Riot servers. It would be possible to use a requests proxy if the login token that's given when logging in on Riot website works for logging in the client (the client might still rate limit logging in that way). I'll test  it out later.

**Comment by ariabox** [comment]
I understand, when will you push an update for dev branch

**Comment by DeviatorZ** [comment]
Pushed an update to the dev branch. I didn't add an API key setting in GUI yet but you can put it in config.py if you wish to use it today.

**Comment by zasaky** [comment]
Thank you very much friend @DeviatorZ , sadly i myself am not a tech person so i do not know how to perform such task. I will paitiently wait nontheless for you to publicly do a update here on github. Please take your time to perform the necessary changes without any hesitation :)

**Comment by DeviatorZ** [comment]
I pushed an update to the main branch. The API key can now be specified in the GUI.

**Comment by ariabox** [comment]
Currently it's working very well! Appreciated.
