### ISSUE TITLE
In game name from user:pass?

### ISSUE THREAD

**Issue by meOWW-cat-byte-me** [DeviatorZ/league-account-checker#62]
Does this export the in game name from user:pass?
I have 200 accs I need to get the ingame names from, so I can make some sort of auto updating rank systemfor my discord bot.
 List of champions would be cool also.
 Thanks

**Comment by karimawii** [comment]
Yes it does, here's all the data it can export: https://github.com/DeviatorZ/league-account-checker/blob/main/templates/single/exampleJson.txt

**Comment by alexuk79** [comment]
@meOWW-cat-byte-me can you please tell me what discord bot name you use for that?

**Comment by meOWW-cat-byte-me** [comment]
> @meOWW-cat-byte-me can you please tell me what discord bot name you use for that?

it's a bot i'm making atm

**Comment by meOWW-cat-byte-me** [comment]
Is there any ways to know which accs are phone verified for clash?

**Comment by nekrusss** [comment]
@meOWW-cat-byte-me sadly, no (maybe yet, we dont know)

**Comment by meOWW-cat-byte-me** [comment]
Is there a way to select only the data I want such as
user:pass
ign
be
champions
rank

**Comment by DeviatorZ** [comment]
Yes. You can create your own template files.
