### ISSUE TITLE
help me plz 

### ISSUE THREAD

**Issue by fer3awn** [DeviatorZ/league-account-checker#68]
cd pathToChecker (e.g. cd C:\Users\magdi\Desktop\league-account-checker-main).
![image](https://github.com/DeviatorZ/league-account-checker/assets/142749948/a4c92cd7-d285-4f22-b9a7-3995ec5dad1d)

**Comment by zasaky** [comment]
Hello, remove the word "patchtochecker"
Leave it as:

cd C:\Users\magdi\Desktop .................................

This will fix the problem

**Comment by fer3awn** [comment]
didnt work

**Comment by DeviatorZ** [comment]
cd C:\Users\magdi\Desktop\league-account-checker-main
