### ISSUE TITLE
main.pyw don't open

### ISSUE THREAD

**Issue by bilbil5** [DeviatorZ/league-account-checker#69]
it used to work but now it won't open. why?

**Comment by bilbil5** [comment]
@zasaky hello. i did pip install -r requirements.txt and still not opening

**Comment by DeviatorZ** [comment]
right-click on main > Edit with IDLE (you might now have this option if you've installed Python from the Microsoft Store) > F5 > You'll see the error in the output. Make sure you get the newest version.

**Comment by DeviatorZ** [comment]
There's a dependency issue with Python 3.12. Use 3.8 - 3.11
