### ISSUE TITLE
Capmonster.cloud Pricing

### ISSUE THREAD

**Issue by zasaky** [DeviatorZ/league-account-checker#70]
Hello,
I've downloaded and installed the new version of the Account Checker. I've noticed that now it is necessary to pay Capmonster.cloud service and provide our API key to the program for it to work.

I would like to know how does it work. So, for each account that it checks it will requiere 1 captcha check correct? 
Also, what is the captcha that is used during the login process? Because i've seen in the website that different types of captchas have a different price.

I havent added funds to my account because i am not sure of how much it would cost me to check for example, 100 accounts.
May you please provide a quick explaination?

Thank you

**Comment by DeviatorZ** [comment]
Hi, it's used for each login. So if you get errors it might require a relog which will need a captcha again. Login uses hCatpcha which costs 0.8$ per 1000.
