### ISSUE TITLE
Captcha error, Riot client v71

### ISSUE THREAD

**Issue by ariabox** [DeviatorZ/league-account-checker#72]
Hi, after Riot Client v71 update, captcha solving doesn't work. 
CapMonsterCloud Failed: [ERROR_CAPTCHA_UNSOLVABLE] This type of captchas is not supported by the service or the image does not contain an answer, perhaps it is too noisy. It could also mean that the image is corrupted or was incorrectly rendered. .

**Comment by DeviatorZ** [comment]
H, how often does it happen? Can't replicate it.

**Comment by zasaky** [comment]
Hello friend, i tried 140 accounts today and it was happening quite often. i would say every 2 accounts it happened.  But 1 week ago i did it with 200 acounts and it only happened once. So i wouldn't know. also, 1 week ago i did with 2 threads and today was with 5 threads. Also i was playing while it was working so i dont know if it affects.

**Comment by ariabox** [comment]
With Riot client v70 i wasn't getting any captcha error but with Riot client v71 almost every checking gives captcha error

**Comment by DeviatorZ** [comment]
Added riot client version extraction for user-agent in dev branch (need to run requirements install). Let me know if that helps.

**Comment by ariabox** [comment]
Thanks for update, I previously received errors with v71, so I obtained Riot Client v70 from another computer, and I'm using that. However, I think it might work if it automatically updates to v71 again. I can try that then. Thank you.
