### ISSUE TITLE
LeagueConnection:RequestException - GET : /lol-matchmaking/v1/search : Retry limit exceeded. Retrying...

### ISSUE THREAD

**Issue by ddgrm5** [DeviatorZ/league-account-checker#73]
https://i.imgur.com/wkgApNE.png
I can't really figure out what this error means, I would appreciate some help.

**Comment by DeviatorZ** [comment]
Hi, Riot made it so you can't queue up with outdated clients anymore (used for checking for low prio) so you have to update the game. I might add an option to disable low prio check in the future as not everyone needs and it doesn't work with level 1 accounts and so on.

**Comment by ddgrm5** [comment]
I'm pretty sure I have the game updated. I'm able to queue and play matches(I just finished one right before typing this), and the versions tab says this: https://i.imgur.com/XSDjZ8y.png

**Comment by DeviatorZ** [comment]
Have you tried running with 1 thread? It could be that you're missing en_GB locale (used by checker) and running with 1 thread would allow the checker to update the client (no other riot client should be open during this)

**Comment by ddgrm5** [comment]
I ran it with 1 thread and it updated, but I'm still getting the same issue. I'm not sure if I'm supposed to stay on 1 thread, or go back to previous settings after updating, but I tried both and still got the issue.

**Comment by DeviatorZ** [comment]
I pushed an update (need to rerun requirements install). You can enable low prior check skipping (in Settings tab) for now. I'll try to replicate the issue later.

**Comment by ddgrm5** [comment]
Thank you, it works with the new setting.
