### ISSUE TITLE
LeagueConnection:SessionException - Session timed out. 

### ISSUE THREAD

**Issue by zasaky** [DeviatorZ/league-account-checker#75]
Hello,
I would like to inform an issue:
![image](https://github.com/DeviatorZ/league-account-checker/assets/143029351/18ef5a15-00d2-4cb1-97d6-4f5c9794189c)

I am using the last published version 4 days ago and i am using capmonster service. Also my internet conection is working fine.
I am using windows 11 64bits
i installed they Phyton version indicated as well as the pip install requierements. 

How can i solve this?
Any information necessary please let me know
thank you

**Comment by zasaky** [comment]
By the way, the first 10 accounts worked fine. The rest kept giving this error.
Thank you very much

**Comment by DeviatorZ** [comment]
Hi, does it always happen and how many threads are you running?

**Comment by zasaky** [comment]
Hello friend,
I am very appreciative of your response. I've been trying for the last 4 days always having the same problem. I will explain the situation

I had like 200 accounts that i wanted to check. These accounts awere from 8 different servers. I put them all together in the same .txt file and let the program run. 
At first i was doing 5 threads and it was giving me the error shown in the picture every once in a while until it completely stopped working.  So i reducced to 2 threads and it worked for a while and then started giving the same error again.

today i tried again but this time i did 1 thread and now it is working perfectly. 
I am 100% positive that it is not CPU/RAM issue, as i have 32 GB DDR5 Ram and Intel Core i7-13700H

Now, if i were to guess, i would say that the problem might be that when running more than 1 thread each thread gets a different server because accounts are from different servers therefore it tries to run the client and patch and it fails so it gives error like shown in the image. 

Summary: I am using 1 thread now and it is working perfectly. Slow but flawlessly.
Once again, i am appreciative of your input, if there's any extra informationthat i can provide, please let me know. Otherwise, we can consider the issue resolved.

**Comment by DeviatorZ** [comment]
Could you send the responses of "GET : /lol-login/v1/session : ()" from the log file (log.txt in the main folder)? 

2023-09-04 23:55:48 - root - DEBUG - GET : /lol-login/v1/session : () {'allow_redirects': True}
2023-09-04 23:55:58 - root - DEBUG - 200 : {"accountId":123,"connected":true,"error":null,"idToken":"LOG","isInLoginQueue":false,"isNewPlayer":false,"puuid":"LOG","state":"SUCCEEDED","summonerId":null,"userAuthToken":"","username":"LOG"}

It should look like this (don't forget to hide user info).

**Comment by DeviatorZ** [comment]
It was caused by TH server needing a different patch. It is not solvable outside of running 1 thread when running a mix of accounts from TH and other servers.
