### ISSUE TITLE
capmonster.cloud Failed 

### ISSUE THREAD

**Issue by Langkurst** [DeviatorZ/league-account-checker#77]
Hi, I keep getting the following error with no idea how to fix.

2023-09-24 12:13:47 [ERROR] capmonster.cloud Failed: Cannot create task. Status code: 403.
2023-09-24 12:13:47 [ERROR] Failed to get Captcha token. Retrying...

I have added the owner on discord with the name Vol.
Hopefully i can get some assitance!
I also have a  24hour API key if that helps.

Thanks!
Lang

**Comment by DeviatorZ** [comment]
Hi, you need to get and use your own API key. https://capmonster.cloud/
403 - no API key set in the captcha tab.
402 - no balance in capmonster.cloud
