### ISSUE TITLE
The requested address is not valid in its context: /rso-auth/v2/authorizations

### ISSUE THREAD

**Issue by ariabox** [DeviatorZ/league-account-checker#91]
Hello, it seems login to client is not working with checker now:
DEBUG - POST : /rso-auth/v2/authorizations : () {'data': None, 'json': {'clientId': 'riot-client', 'trustLevels': ['always_trusted']}}
DEBUG - POST : /rso-auth/v2/authorizations : () {'data': None, 'json': {'clientId': 'riot-client', 'trustLevels': ['always_trusted']}}
DEBUG - POST : /rso-auth/v2/authorizations : () {'data': None, 'json': {'clientId': 'riot-client', 'trustLevels': ['always_trusted']}}
DEBUG - POST : /rso-auth/v2/authorizations : () {'data': None, 'json': {'clientId': 'riot-client', 'trustLevels': ['always_trusted']}}
ERROR - xxx RiotConnection - Connection failure. Retrying...

:
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018AE92B74D0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context')': /rso-auth/v2/authorizations

**Comment by DeviatorZ** [comment]
Hi, RIot client didn't open in time. Most likely you're running too many threads for your device specs or if running one thread and you have a different client open (when running 1 thread patching is enabled so the client won't open if another already is)

**Comment by DeviatorZ** [comment]
Added automatic cleanup, shouldn't have issues when running 1 thread anymore
