### ISSUE TITLE
Failed: Cannot create task. Status code: 403. Why ?..

### ISSUE THREAD

**Issue by SURLAWIFIDUMCDO** [DeviatorZ/league-account-checker#96]
How i can resolve this error please ?

**Comment by SURLAWIFIDUMCDO** [comment]
![Uploading error.JPG…]()

**Comment by DeviatorZ** [comment]
You need to get an API key and add balance for the checker to work.  You can do that in captcha tab.
I recommend using capmonster as capsolver currently doesn't work - https://capmonster.cloud/en/

**Comment by SURLAWIFIDUMCDO** [comment]
> You need to get an API key and add balance for the checker to work. You can do that in captcha tab. I recommend using capmonster as capsolver currently doesn't work - https://capmonster.cloud/en/

Same problem, also i have an API key...

![error](https://github.com/DeviatorZ/league-account-checker/assets/128741241/849bd756-7748-4480-a1a8-59d9ee0373f6)
![key](https://github.com/DeviatorZ/league-account-checker/assets/128741241/b9383d05-210e-4e88-a165-8e1f83aff962)

Why ?

**Comment by DeviatorZ** [comment]
Did you add money to your balance?
The HTTP 402 status code indicates that the client must make a payment to access the requested resource

**Comment by SURLAWIFIDUMCDO** [comment]
> Did you add money to your balance? The HTTP 402 status code indicates that the client must make a payment to access the requested resource

I need to pay for have a API key who work ?

**Comment by DeviatorZ** [comment]
yes
